#!/bin/sh

(
find bin lib t scripts \( -name '*.pm' -o -name '*.pl' -o -name '*.t' \) -print -exec perltidy -b {} \; | xargs echo 'TIDY:'

find bin lib t scripts -name '*.bak' -print -exec rm -f {} \; | xargs echo '  RM:'
) > &2
