#!/bin/sh

DIRLIST="bin lib t scripts"

(
find $DIRLIST \( -name '*.pm' -o -name '*.pl' -o -name '*.t' \) -print -exec perltidy -b {} \; | xargs -n 1 echo 'TIDY:'

find $DIRLIST -name '*.bak' -print -exec rm -f {} \; | xargs -n 1 echo '  RM:'
) >&2
